# Generated by Django 3.2.9 on 2021-11-30 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211121_0405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'managed': True, 'ordering': ['published'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blog'},
        ),
    ]
